### ISSUE TITLE
Customizing disallowed keywords

### ISSUE THREAD

**Issue by eitanp461** [btford/grunt-ddescribe-iit#1]
Hi,

This is a great task :) Thanks for sharing.

In my project it is ok to exclude a test spec/suite temporarily for "offline" build failure analysis.
However it is not ok to push iit/ddescribe to run exclusively in CI.

Can you add a configuration option that enables listing the violations?

Thanks,
Eitan

**Comment by davidparsson** [comment]
This would be awesome!

**Comment by mzgol** [comment]
Fixed in 0.0.5.

**Comment by mtrias** [comment]
:beer:

**Comment by davidparsson** [comment]
Thank you!

**Comment by lostplan** [comment]
This is really awesome. Thanks!
