### ISSUE TITLE
fdescribe/fit

### ISSUE THREAD

**Issue by mzgol** [btford/grunt-ddescribe-iit#12]
karma-jasmine >=0.3.4 now supports `fdescribe/fit` which are native Jasmine 2.x equivalents for `ddescribe`/`iit`. This task should catch them.

BTW, karma-jasmine 0.3.3 dropped `ddescribe`/`iit` as well... (https://github.com/karma-runner/karma-jasmine/issues/73) Not sure if that's a long-term plan but if it is then maybe the task name should be changed. ;)

**Comment by scriby** [comment]
+1
