### ISSUE TITLE
xit and iit are matched in commented out code

### ISSUE THREAD

**Issue by jrencz** [btford/grunt-ddescribe-iit#7]
```
// iit('should...' function() {})  // this fails
```

**Comment by mzgol** [comment]
The `ddescribe-iit` task uses regexes to catch function names for speed purposes. Full comment parsing would require AST support. Now, just commenting out lines at their beginnings would be simpler but it would still require splitting the source into lines and matching these lines.

The branch [multiline-matching](https://github.com/btford/grunt-ddescribe-iit/tree/multiline-matching) implements this logic for testing purposes. It takes about 50% more time than current version and it only covers specific use cases so I'm afraid there's no acceptable fix in the current architecture.

**Comment by mzgol** [comment]
Using Esprima might increase the required time a lot, see #2.

**Comment by mzgol** [comment]
I'm closing it as something that would be hard to achieve while maintaining speed and not complicating code with special-casing code like that.

If any concrete proposal emerges, I might reopen.
